version: "3.3"
services:
  cockroach_1:
    image: cockroachdb/cockroach:v2.1.0
    command:
      - "start"
      - "--insecure"
      - "--join=cockroach_1,cockroach_2,cockroach_3"
    volumes:
      - cockroach_1:/cockroach/cockroach-data

  cockroach_2:
    image: cockroachdb/cockroach:v2.1.0
    command:
      - "start"
      - "--insecure"
      - "--join=cockroach_1,cockroach_2,cockroach_3"
    volumes:
      - cockroach_2:/cockroach/cockroach-data

  cockroach_3:
    image: cockroachdb/cockroach:v2.1.0
    command:
      - "start"
      - "--insecure"
      - "--join=cockroach_1,cockroach_2,cockroach_3"
    volumes:
      - cockroach_3:/cockroach/cockroach-data

  cockroach_init:
    image: cockroachdb/cockroach:v2.1.0
    command:
      - "init"
      - "--insecure"
      - "--host=cockroach_1"
    depends_on:
      - cockroach_1
      - cockroach_2
      - cockroach_3

  cockroach_client:
    image: cockroachdb/cockroach:v2.1.0
    entrypoint: "bash"

volumes:
  cockroach_1:
  cockroach_2:
  cockroach_3:
